name: Build with cargo

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    name: Build (and maybe deploy?)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: target/**
          key: ${{ runner.os }}-cargo
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Generate HTML
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --release
      - name: Deploy built files
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push' }}
        with:
          folder: build/
          branch: rendered
